package com.philips.ibec.functionLibrary;

import java.util.logging.Logger;
import io.restassured.RestAssured;
import io.restassured.http.Method;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;

public class eMR_FunctionsLib extends genericFunctionLib {
	
	final static Logger logger= Logger.getLogger("EMR_FunctionsLib");
	
	public static void sendMessage_toEMRA()
	{   
	
		RestAssured.baseURI = "http://restapi.demoqa.com/utilities/weather/city";
	
		RequestSpecification httpRequest = RestAssured.given();
	
		Response response = httpRequest.request(Method.GET, "/Hyderabad");

		String responseBody = response.getBody().asString();
		System.out.println("Response Body is =>  " + responseBody);
		
		logger.info("this is the log message generated by the Logger ");
		

	}
  
	
	public static void downloadBundleEMR()
	{
		
	}
    
	public static void splitBundle()
	{
		
	}
	

}